version: '3.0'

services:
  app1:
    image: nginx:stable-alpine
    container_name: app1
    restart: on-failure
    # env_file: configs/frontend_develop.env
    ports:
      - 3000:80
    networks:
      - mynet

  app2:
    image: nginx:stable-alpine
    container_name: app2
    restart: always
    # env_file: configs/backend_develop.env
    ports:
      - 5000:80
    networks:
      - mynet

  nginx:
    image: nginx-reverse-proxy
    container_name: nginx
    restart: always
    depends_on:
      - app1
      - app2
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynet

networks:
    mynet: